# Generated by Django 5.1.5 on 2025-02-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_alter_chat_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasted_messages', to='chatApp.user')),
            ],
        ),
    ]
