# Generated by Django 5.1.5 on 2025-02-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_message_file_attachment_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
